<?php require('template/header.phtml') ?>

    <div class="container">
        <div class="row">
            <div class="col">
                <h1>An error has occurred.</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <br/>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h4>Please contact the system administrator.</h4>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        View Error
                    </button>
                    <ul class="dropdown-menu">
                        <li class="dropdown-item">
                            <p>test</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<?php require('template/footer.phtml') ?>