<?php require_once('template/header.phtml') ?>

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Friend Map</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div id="map" class="map">
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.13.0/build/ol.js"></script>
<!--<script src="js/map.js"></script>-->
<script type="text/javascript">var token = "<?php echo $_SESSION['ajaxToken'] ?>"</script>
<script type="text/javascript" src="ajax/loadLocations.js"></script>

<?php require_once('template/footer.phtml') ?>
