<?php

require_once("template/header.phtml");

if ($view->duplicate) {
    echo '
    <div class="container" id="duplicateAlert">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>This username is already taken.</strong> Please choose another one.
        </div>
    </div>
    ';
} ?>

<div class="container">
    <div class="row">
        <div class="col-4">
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h1>Register</h1>
                    </div>
                    <div class="row">
                        <p>(*) Required</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <!--Form to capture new users details-->
                <form action="register.php" method="POST" class="register-form">
                    <div class="row">
                        <div class="col">
                            <label for="username"><b>Username*</b></label>
                        </div>
                        <div class="col">
                            <input id="usernameInput" type="text" placeholder="Username" name="username" class="registerinput <?php if($view->duplicate) { echo 'border-danger'; }; ?>" required <?php if ($view->duplicate) { echo 'value="' . $view->username . '"'; } ?> data-bs-toggle="tooltip" data-bs-placement="right" title="This username is already taken.">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="fname"><b>First name*</b></label>
                        </div>
                        <div class="col">
                            <input type="text" placeholder="First name" name="fname" class="registerinput" required <?php if ($view->duplicate) { echo 'value="' . $view->fname . '"'; } ?>>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="lname"><b>Last name*</b></label>
                        </div>
                        <div class="col">
                            <input type="text" placeholder="Last name" name="lname" class="registerinput" required <?php if ($view->duplicate) { echo 'value="' . $view->lname . '"'; } ?>>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="email"><b>Email*</b></label>
                        </div>
                        <div class="col">
                            <input type="text" placeholder="Email" name="email" class="registerinput" required <?php if ($view->duplicate) { echo 'value="' . $view->email . '"'; } ?>>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="password"><b>Password*</b></label>
                        </div>
                        <div class="col">
                            <input type="password" placeholder="New Password" name="password" class="registerinput"
                                   required>
                        </div>
                    </div>
                    <div class="row form-padding">
                        <button type="submit" name="registerButton" class="btn btn-primary btn-block" id="regButton">Register</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-2">

        </div>
        <div class="col-6">
            <div class="row">
                <div class=" p-5 mb-4 bg-light rounded-3">
                    <div class="container-fluid py-5">
                        <h1 class="display-5 fw-bold">Create User Account</h1>
                        <p class="col-md-8 fs-4">
                            Please enter your details here to register.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="js/popper.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/dupUsernameTooltip.js"></script>