<?php require('template/header.phtml') ?>

    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Users</h1>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <form>
                    <input type="text" placeholder="Search..." class="form-control" id="searchbox">
                </form>
                <div id="liveSearch" class="search-infront"></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <table class="table table-striped" data-toggle="table" data-search="false" data-show-columns="true" data-pagination="true">
                    <thead>
                    <tr>
                        <th scope="col">User ID</th>
                        <th scope="col">Image</th>
                        <!--Displays further user information if a user is plugged in-->
                        <?php
                        if (isset($_SESSION['login'])) {
                            echo
                            '
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                            ';
                        }
                        ?>
                        <th scope="col">Username</th>
                        <?php
                        if (isset($_SESSION['login'])) {
                            echo
                                '<th scope="col">Actions</th>';
                        }
                        ?>
                    </tr>
                    </thead>
                    <tbody>
                    <!--Creates a new row for each user returned-->
                    <?php foreach ($view->dataset as $dataset) {
                        echo '<tr>' .
                            '<th scope="row">' . $dataset->getUserid() . '</th>' .
                            '<td><img width="80px" src="images/' . $dataset->getPhoto() . '" alt="' . $dataset->getUsername() . '"' . '></td>';
                        if (isset($_SESSION['login'])) {
                            echo

                                '<td>' . $dataset->getFname() . '</td>' .
                                '<td>' . $dataset->getLname() . '</td>';
                        }
                        echo '<td>' . $dataset->getUsername() . '</td>';
                        if (isset($_SESSION['login'])) {
                            echo
                                '<td>
                                    <form method="post" action="" class="btn-pad" text-primary>
                                        <input type="hidden" value="' . $dataset->getUserid() . '" name="friendID">
                                        <div class="row">
                                            <input type="submit" name="requestFriend" value="Request" class="btn btn-primary btn-block">
                                        </div>
                                        <div class="row">
                                            <input type="submit" name="blockUser" value="Block" class="btn btn-danger btn-block">
                                        </div>
                                    </form>
                                </td>' .
                                '</tr>';
                        }
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<script src="js/searchUser.js"></script>

<?php require('template/footer.phtml') ?>


<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <img src="" alt="">
            </div>
        </div>
        <div class="col">
            <div class="row">
                <h5><strong>uname</strong> (uid)</h5>
            </div>
            <div class="row">
                <p>fname lname</p>
            </div>
        </div>
    </div>
</div>
