<?php require('template/header.phtml');
$usernameChecked = false;
$fnameChecked = false;
$lnameChecked = false;
if (!isset($_POST['search'])) {
    $usernameChecked = true;
    $fnameChecked = true;
    $lnameChecked = true;
} else {
    if (isset($_POST['usernameCheck'])) {
        $usernameChecked = true;
    }
    if (isset($_POST['fnameCheck'])) {
        $fnameChecked = true;
    }
    if (isset($_POST['lnameCheck'])) {
        $lnameChecked = true;
    }
}
?>


    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Users</h1>
            </div>
        </div>
    </div>
    <?php if (isset($_SESSION['login'])) {
        echo '<div class="container">
        <div class="row">
            <div class="col">
                <form type="submit" action="" method="POST" autocomplete="off">
                    <div class="input-group mb-3">
                        <input type="text" placeholder="Search..." class="form-control" id="searchbox" name="searchTerm"';
        if (isset($_POST['search'])) { echo 'value=' . $_POST['searchTerm']; }
        echo '>
                        <div class="input-group-text"><input class="form-check-input" type="checkbox" name="usernameCheck" value="true" id="usernameCheck" aria-label="Checkbox for following text input" '; if ($usernameChecked) { echo 'checked'; }; echo '><label class="form-check-label" for="usernameCheck">Username</div>
                        <div class="input-group-text"><input class="form-check-input" type="checkbox" name="fnameCheck" value="true" id="fnameCheck" aria-label="Checkbox for following text input" '; if ($fnameChecked) { echo 'checked'; }; echo '><label class="form-check-label" for="fnameCheck">First Name</div>
                        <div class="input-group-text"><input class="form-check-input" type="checkbox" name="lnameCheck" value="true" id="lnameCheck" aria-label="Checkbox for following text input" '; if ($lnameChecked) { echo 'checked'; }; echo '><label class="form-check-label" for="lnameCheck">Last Name</div>
                        <input type="number" placeholder="#" class="form-control" id="limit" name="limit" style="max-width: 4rem;" value="';
        if (isset($_POST['search'])) {
            echo $_POST['limit'];
        }
        echo '">
                        <button class="btn btn-outline-secondary" type="submit" id="searchButton" name="search">Search</button>
                    </div>
                </form>
                <div id="liveSearch" class="search-infront"></div>
            </div>
        </div>';
    } ?>

    <div class="container">
        <div class="row">
            <div class="col">
                <table class="table table-striped" data-toggle="table" data-search="false" data-show-columns="true" data-pagination="true">
                    <thead>
                    <tr>
                        <th scope="col">User ID</th>
                        <th scope="col">Image</th>
                        <?php
                        if (isset($_SESSION['login'])) {
                            echo
                            '
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                            ';
                        }
                        ?>
                        <th scope="col">Username</th>
                        <?php
                        if (isset($_SESSION['login'])) {
                            echo
                            '<th scope="col">Actions</th>';
                        }
                        ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($view->dataset as $dataset) {
                        echo '<tr>' .
                            '<th scope="row">' . $dataset->getUserid() . '</th>' .
                            '<td><img width="80px" src="images/' . $dataset->getPhoto() . '" alt="' . $dataset->getUsername() . '"' . '></td>';
                        if (isset($_SESSION['login'])) {
                            echo

                                '<td>' . $dataset->getFname() . '</td>' .
                                '<td>' . $dataset->getLname() . '</td>';
                        }
                        echo '<td>' . $dataset->getUsername() . '</td>';
                        if (isset($_SESSION['login'])) {
                            echo
                                '<td><div class="container">
                                    <form method="post" action="" class="btn-pad" text-primary>
                                        <input type="hidden" value="' . $dataset->getUserid() . '" name="friendID">
                                        <div class="row">
                                            <input type="submit" name="requestFriend" value="Request" class="btn btn-primary btn-block">
                                        </div>
                                        <div class="row">
                                            <input type="submit" name="blockUser" value="Block" class="btn btn-danger btn-block">
                                        </div>
                                        <div class="row">
                                            <a class="btn btn-secondary btn-block" href="user.php?userid=' . $dataset->getUserid() . '">View Profile</a>
                                        </div>
                                    </form>
                                </td></div>' .
                                '</tr>';
                        }
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

<script type="text/javascript">let token = "<?php echo $_SESSION['ajaxToken'] ?>"</script>
<script type="text/javascript" src="ajax/searchUser.js"></script>

<?php require('template/footer.phtml') ?>

