<?php include_once('template/httpsredirect.php') ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Page meta data-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Daniel Roberts">

    <!--Bootstrap-->
    <!--<link href="css/bootstrap.css" rel="stylesheet">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--Bootstrap tables-->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css">
    <!--Personal style sheet-->
    <link href="css/style.css" rel="stylesheet">

    <title>Friends - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<!-- nav bar-->
<div class="container-fluid px-0">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm p-3 mb-5 bg-white rounded">
        <div class="container px-03">
            <a class="navbar-brand" href=".">Friends</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="./index.php">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./users.php">Users</a>
                    </li>
                    <?php
                    if (isset($_SESSION["login"])) {
                        echo '
                    <li class="nav-item">
                        <a class="nav-link" href="myfriends.php">My Friends</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="myrequests.php">My Requests</a>
                    </li>
                    <li>
                        <a class="nav-link" href="map.php">Map</a>
                    </li>';
                    }
                    ?>
                </ul>
            </div>
            <!-- displays the login boxes if not logged in, or profile button and logout button if they are.-->
            <div class="d-flex">
                <?php
                if (!isset($_SESSION["login"])) {
                    echo '
                <form method="post" action="" class="form text-primary">
                    <label for="username">Username</label>
                    <input class="logininput" type="text" name="username">
                    <label for="password">Password</label>
                    <input class="logininput" type="password" name="password">
                    <input type="submit" name="loginbutton" value="Login" class="btn btn-primary">
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="register.php">Register</a>
                    </li>
                </ul>
                    ';
                } else {
                    echo '
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link">Hello, ' . $_SESSION['fname'] . '</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="profile.php">My Profile</a>
                    </li>
                </ul>
                <form method="post" action="" class="form text-primary">
                    <input type="submit" name="logoutbutton" value="Logout" class="btn btn-primary">
                </form>
                ';
                }
                ?>
            </div>
        </div>
    </nav>
</div>